services:
- type: web
  name: taskly-backend
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app
  repo: https://github.com/tu-usuario/taskly-backend.git  # Reemplaza con tu repositorio
  autoDeploy: true
  envVars:
  - key: JWT_SECRET_KEY
    generateValue: true
  - key: FLASK_APP
    value: app.py
  - key: FLASK_ENV
    value: production